In [3]:
# NUMPY ARRAY FUNCTION
# INCREAMENT WITH EACH ELEMENT


import numpy as np

arr = np.array([1,2,3,4,5])

arr = arr + 5

print(arr.dtype)

int64


In [4]:
# ADDING TWO ARRAY

import numpy as np

arr_1 = np.array([1,2,3,4,5])

arr_2 = np.array([1,2,3,4,5])

arr_3 = arr_1 + arr_2

print(arr_3)

[ 2  4  6  8 10]


In [13]:
# MATHEMATICAL FUNCTION USING ARRAY

#import numpy as np

from numpy import *  # THIS IMPORT ALL FUNCTION IN THE NUMPY ARRAY

arr = np.array([1,2,3,4,5])

print("sin\n",sin(arr))

print("\nlog\n",log(arr))

print("\nsqrt\n",sqrt(arr))

print("\nminimum\n",min(arr))

print("\nmaximum\n",max(arr))

sin
 [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]

log
 [0.         0.69314718 1.09861229 1.38629436 1.60943791]

sqrt
 [1.         1.41421356 1.73205081 2.         2.23606798]

minimum
 1

maximum
 5


In [15]:
# ARRAY CONCATENATE FUNCTION

import numpy as np

arr_1 = np.array([1,2,3,4,5])

arr_2 = np.array([6,7,8,9,10])

arr = concatenate([arr_1,arr_2])

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [24]:
# ARRAY COPY FUNCTION

import numpy as np

arr_1 = np.array([1,2,3,4,5])

arr_2 = arr_1

print(arr_2)

print("\nAddress of arr_1 : ",id(arr_1))

print("\nAddress of arr_2 : ",id(arr_2))

[1 2 3 4 5]

Address of arr_1 :  132772473425808

Address of arr_2 :  132772473425808


In [30]:
# COPY USING VIEW FUNCTION

import numpy as np

arr_1 = np.array([1,2,3,4,5])

arr_2 = arr_1.view()

print(arr_1)

print(arr_2)

print("\nAddress of arr_1 : ",id(arr_1))

print("\nAddress of arr_2 : ",id(arr_2))

# COPY USING view() function it copy the array with different address

[1 2 3 4 5]
[1 2 3 4 5]

Address of arr_1 :  132772471587344

Address of arr_2 :  132772471587248


In [37]:
# SHALLOW() COPY 

import numpy as np

arr_1 = np.array([1,2,3,4,5])

arr_2 = arr_1.view()

arr_1[0] = 100   # THE CHANGE ELEMENT AFFECT THE COPY ARRAY. THIS IS SHALLOW COPY

print("\nArray_1 : ",arr_1)

print("\nArray_2 : ",arr_2)


Array_1 :  [100   2   3   4   5]

Array_2 :  [100   2   3   4   5]


In [36]:
# DEEP() COPY

import numpy as np

arr_1 = np.array([1,2,3,4,5])

arr_2 = arr_1.copy()

arr_1[0] = 100   # THE ELEMENT CHANGE ONLY THE FIRST ARRAY NOT CHANGE THE SECOND ARRAY. THIS IS DEEP COPY

print("\nArray_1 : ",arr_1)

print("\nArray_2 : ",arr_2)


Array_1 :  [100   2   3   4   5]

Array_2 :  [1 2 3 4 5]
