In [2]:
# NUMPY ARRAY

# ARRAY()

from numpy import *

arr = array([1,2,3,4,5])

print(arr)

print(arr.dtype)

[1 2 3 4 5]
int64


In [7]:
# LINSPACE()

# SYNTAX:
#    linspace(start,stop,restep)

from numpy import *

arr_1 = linspace(1,15)

print(arr_1)

print("\n")

arr_2 = linspace(1,15,20)

print(arr_2)

[ 1.          1.28571429  1.57142857  1.85714286  2.14285714  2.42857143
  2.71428571  3.          3.28571429  3.57142857  3.85714286  4.14285714
  4.42857143  4.71428571  5.          5.28571429  5.57142857  5.85714286
  6.14285714  6.42857143  6.71428571  7.          7.28571429  7.57142857
  7.85714286  8.14285714  8.42857143  8.71428571  9.          9.28571429
  9.57142857  9.85714286 10.14285714 10.42857143 10.71428571 11.
 11.28571429 11.57142857 11.85714286 12.14285714 12.42857143 12.71428571
 13.         13.28571429 13.57142857 13.85714286 14.14285714 14.42857143
 14.71428571 15.        ]


[ 1.          1.73684211  2.47368421  3.21052632  3.94736842  4.68421053
  5.42105263  6.15789474  6.89473684  7.63157895  8.36842105  9.10526316
  9.84210526 10.57894737 11.31578947 12.05263158 12.78947368 13.52631579
 14.26315789 15.        ]


In [9]:
#ARANGE()

# SYNTAX:
#     arange(start,stop,step)

from numpy import *

arr = arange(1,10)

print(arr)

print("\nArange using Step\n")

arr = arange(10,50,2)

print(arr)

[1 2 3 4 5 6 7 8 9]

Arange using Step

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [21]:
# LOGSPACE

#SYNTAX:
#   logspace(start,stop,divide)

import numpy as np

arr = np.logspace(1,40,10)

print(arr)

print('%2f'%arr[0])

[1.00000000e+01 2.15443469e+05 4.64158883e+09 1.00000000e+14
 2.15443469e+18 4.64158883e+22 1.00000000e+27 2.15443469e+31
 4.64158883e+35 1.00000000e+40]
10.000000


In [28]:
# ZEROS

#SYNTAX:
#   zero(size)

import numpy as np

arr = np.zeros(10)

print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [34]:
#ONES

# SYNTAX:
#        ones(size)

import numpy as np

arr = np.ones(10)

print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
