In [4]:
# ONE DIMENSIONAL ARRAY

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

print(arr[4:]) 

print(arr[:4]) 

[2 3 4 5]
[5 6 7]
[1 2 3 4]


In [5]:
# NEGATIVE SLICIING IN ONE DIMENSIONAL ARRAY

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1]) 

[5 6]


In [8]:
# STEP IN SLICING

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2]) 

print(arr[::2]) 

[2 4]
[1 3 5 7]


In [14]:
# TWO DIMENSIONAL ARRAY

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4]) 

print(arr[0:2, 2]) 

print(arr[0:2, 1:4]) 

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]
